#print('Save')
func_list = [self.checkBox_8.isChecked,
            self.spinBox_10.value,
            self.spinBox_11.value,
            self.checkBox_9.isChecked,
            self.spinBox_12.value,
            self.spinBox_13.value,
            self.checkBox_10.isChecked,
            self.spinBox_14.value,
            self.spinBox_15.value,
            self.checkBox_11.isChecked,
            self.spinBox_16.value,
            self.spinBox_17.value,
            self.checkBox_12.isChecked,
            self.spinBox_18.value,
            self.spinBox_19.value,
            self.checkBox_13.isChecked,
            self.spinBox_20.value,
            self.spinBox_21.value,
            self.checkBox_14.isChecked,
            self.spinBox_22.value,
            self.spinBox_23.value,
            self.checkBox_15.isChecked,
            self.spinBox_24.value,
            self.spinBox_25.value,
            self.checkBox_16.isChecked,
            self.spinBox_26.value,
            self.spinBox_27.value,
            self.checkBox_17.isChecked,
            self.spinBox_28.value,
            self.spinBox_29.value,
            self.checkBox_18.isChecked,
            self.spinBox_30.value,
            self.spinBox_31.value,
            self.checkBox_19.isChecked,
            self.spinBox_32.value,
            self.spinBox_33.value,
            self.spinBox_34.value,
            self.spinBox_35.value]

self.saved_state = [f() for f in func_list]

