#print('Restore')
func_list = [self.checkBox_8.setChecked,
            self.spinBox_10.setValue,
            self.spinBox_11.setValue,
            self.checkBox_9.setChecked,
            self.spinBox_12.setValue,
            self.spinBox_13.setValue,
            self.checkBox_10.setChecked,
            self.spinBox_14.setValue,
            self.spinBox_15.setValue,
            self.checkBox_11.setChecked,
            self.spinBox_16.setValue,
            self.spinBox_17.setValue,
            self.checkBox_12.setChecked,
            self.spinBox_18.setValue,
            self.spinBox_19.setValue,
            self.checkBox_13.setChecked,
            self.spinBox_20.setValue,
            self.spinBox_21.setValue,
            self.checkBox_14.setChecked,
            self.spinBox_22.setValue,
            self.spinBox_23.setValue,
            self.checkBox_15.setChecked,
            self.spinBox_24.setValue,
            self.spinBox_25.setValue,
            self.checkBox_16.setChecked,
            self.spinBox_26.setValue,
            self.spinBox_27.setValue,
            self.checkBox_17.setChecked,
            self.spinBox_28.setValue,
            self.spinBox_29.setValue,
            self.checkBox_18.setChecked,
            self.spinBox_30.setValue,
            self.spinBox_31.setValue,
            self.checkBox_19.setChecked,
            self.spinBox_32.setValue,
            self.spinBox_33.setValue,
            self.spinBox_34.setValue,
            self.spinBox_35.setValue]
if hasattr(self , 'seved_state'):
    for i in range(len(self.seved_state)):
        func_list[i](self.seved_state[i])

